### PR TITLE
direct url downloading update

### PR DESCRIPTION
**Pull request by ShiiRochi**
It relates to the issue #8 

In case of `allowDownloadByUrl` being set to `true`, code will set `target` as '_blank' to 'a' element and will not revokeUrlObject, because it is not created in this case.

### CODE REVIEW

**Comment by nielsboogaard** [comment]
Hi @ShiiRochi, thanks for the PR. Could you do a catchup with the master branch and rebuild the distribution again to get rid of the merge conflicts? After that I'm happy to merge it.

**Comment by ShiiRochi** [comment]
Okay

**Comment by ShiiRochi** [comment]
Hi, @nielsboogaard, I've just fixed conflicts

**Comment by virtualize** [comment]
Hello @nielsboogaard, could you please merge this PR or is there anything preventing you I could possible help with?

**Comment by nielsboogaard** [comment]
@virtualize Sorry for my late reply, was quite busy with other things. I'll have a look at your PR next week, and will merge it when it works ok. Thanks for the work (and your patience 😉 )!

**Comment by cenkakay** [comment]
any updates?

**Comment by ShiiRochi** [comment]
> any updates? 

It seems that I need to make another rebase to resolve conflicts again 🙃

**Comment by ShiiRochi** [comment]
> > any updates?
> 
> It seems that I need to make another rebase to resolve conflicts again 🙃

done)

**Comment by ShiiRochi** [comment]
Also, third argument was added, that is downloadFunction, that can be used to download file directly...however, I updated my changes so that this MR will be either rejected or accepted. If there're some points that are questionable, then @nielsboogaard can write and I will try to adjust them

**Comment by nielsboogaard** [comment]
Sorry for keeping this open so long, and thanks for your patience. Just reviewed the PR, looks fine so will merge it.

**Pull request merged**
