### PR TITLE
Added possibility to download file by URL

### PR DESCRIPTION
**Pull request by jevgenijsp**
Added possibility to download file by URL provided in metadata with key 'url'.

**How to set URL:**
```   
 pondFiles = [{
        // the server file reference
        source: 12345,
        options: {
            // set type to local to indicate an already uploaded file
            type: 'local',
            // mock file information
            file: {
                name: 'my-file.png',
                size: 3001025,
                type: 'image/png'
            },
            // our URL to be possible download
            metadata: {
                url: 'api/files/12345', 
            }
        }
    }];
```

To enable this feature we should set true for 'allowDownloadByUrl' option.

### CODE REVIEW

**Comment by jevgenijsp** [comment]
@nielsboogaard 
Hello, can you please pay attention at this PR? I think it can be useful for someone.

**Comment by nielsboogaard** [comment]
@jevgenijsp Sorry, vacation time over here :)
Thanks for your PR, will have a look at it tomorrow.

**Comment by nielsboogaard** [comment]
Released v1.0.1 which includes this new functionality.

**Comment by jevgenijsp** [comment]
> Released v1.0.1 which includes this new functionality.

Thanks! Good to hear that. 👍

**Pull request merged**
